// Generated by `pnpm bindings`; do not edit.

export type CaptureId = string;

export type CaptureSessionId = string;

export type ContextId = string;

export type ContextSourceId = string;

export type DirectorySelectionToken = string;

export type MediaId = string;

export type StagedMediaId = string;

export type Timestamp = string;

export type ErrorCode = "VALIDATION_ERROR" | "STALE_SESSION" | "CONTEXT_REQUIRED" | "CONTEXT_AMBIGUOUS" | "CONTEXT_SOURCE_NOT_FOUND" | "CONTEXT_SOURCE_STALE" | "EMPTY_CAPTURE" | "CAPTURE_NOT_FOUND" | "CONTEXT_NOT_FOUND" | "STORAGE_UNAVAILABLE" | "STORAGE_WRITE_FAILED" | "MEDIA_STAGE_FAILED" | "MEDIA_FINALIZE_FAILED" | "MEDIA_NOT_FOUND" | "UNSUPPORTED_CLIPBOARD_CONTENT" | "PERMISSION_DENIED" | "AUDIO_DEVICE_UNAVAILABLE" | "AUDIO_RECORDING_FAILED" | "AUDIO_PLAYBACK_FAILED" | "SEARCH_FAILED" | "SHORTCUT_CONFLICT" | "MODEL_NOT_AVAILABLE" | "MODEL_DOWNLOAD_FAILED" | "ENRICHMENT_FAILED" | "INTERNAL_ERROR";

export type ErrorDetailKey = "field" | "limit" | "operation" | "permission" | "resourceKind" | "retryAfterMs" | "state";

export type ErrorDetailValue = string | number | boolean | null;

export type ErrorDetails = { [key in ErrorDetailKey]?: ErrorDetailValue };

export type AppError = { code: ErrorCode, message: string, retryable: boolean, details: ErrorDetails, };

export type CommandResult<T> = { ok: true, data: T, } | { ok: false, error: AppError, };

export type CaptureKind = "text" | "image" | "audio";

export type ContextKind = "project" | "standalone";

export type CaptionSource = "user" | "context_generated" | "transcript_generated";

export type ContextProviderKind = "manual" | "vscode" | "shell" | "foreground_window";

export type ContextSourceKind = "vscode_window" | "integrated_terminal" | "external_terminal" | "shell" | "foreground_window";

export type MediaKind = "image" | "audio";

export type CapturePopupLayout = "compact" | "error" | "chooser" | "media";

export type MediaMimeType = "image/png" | "audio/wav";

export type EnrichmentStatus = "not_requested" | "pending" | "completed" | "skipped" | "failed";

export type ContextRef = { id: ContextId, kind: ContextKind, name: string, };

export type SelectedProjectDirectory = { selectedDirectoryToken: DirectorySelectionToken, suggestedName: string, };

export type PickProjectDirectoryResult = { selection: SelectedProjectDirectory | null, };

export type ListContextsInput = { kind: ContextKind | null, query: string | null, limit: number, };

export type ListContextsResult = { contexts: Array<ContextRef>, };

export type CreateContextInput = { "kind": "standalone", name: string, } | { "kind": "project", name: string, selectedDirectoryToken: DirectorySelectionToken, };

export type CreateContextResult = { context: ContextRef, };

export type ContextCandidate = { context: ContextRef, branchName: string | null, provider: ContextProviderKind, requiresConfirmation: boolean, };

export type ContextSelection = { "kind": "live_source", sourceId: ContextSourceId, } | { "kind": "saved_context", contextId: ContextId, };

export type ContextSourceOption = { sourceId: ContextSourceId, kind: ContextSourceKind, provider: ContextProviderKind, applicationName: string, label: string, context: ContextRef, branchName: string | null, isForeground: boolean, };

export type ListCaptureContextSourcesInput = { sessionId: CaptureSessionId, query: string | null, limit: number, };

export type ListCaptureContextSourcesResult = { liveSources: Array<ContextSourceOption>, savedContexts: Array<ContextRef>, };

export type ContextResolution = { "state": "resolved", candidate: ContextCandidate, selection: ContextSelection | null, } | { "state": "ambiguous", candidate: null, selection: null, } | { "state": "required", candidate: null, selection: null, };

export type StagedMedia = { stagedMediaId: StagedMediaId, kind: MediaKind, previewUri: string, mimeType: MediaMimeType, byteSize: number, durationMs: number | null, widthPx: number | null, heightPx: number | null, };

export type RecordingState = { "state": "idle" } | { "state": "recording", elapsedMs: number, } | { "state": "stopped", elapsedMs: number, stagedMediaId: StagedMediaId, };

export type CaptureSession = { sessionId: CaptureSessionId, contextResolution: ContextResolution, stagedMedia: StagedMedia | null, recordingState: RecordingState, };

export type CancelCaptureSessionInput = { sessionId: CaptureSessionId, };

export type CancelCaptureSessionResult = { cancelled: boolean, };

export type DismissCapturePopupResult = { dismissed: boolean, focusRestored: boolean, };

export type SetCapturePopupLayoutInput = { layout: CapturePopupLayout, };

export type SetCapturePopupLayoutResult = { layout: CapturePopupLayout, };

export type SelectCaptureContextSourceInput = { sessionId: CaptureSessionId, selection: ContextSelection, };

export type SaveCaptureResult = { captureId: CaptureId, capturedAt: Timestamp, enrichmentScheduled: boolean, };

export type MediaSummary = { mediaId: MediaId, kind: MediaKind, previewUri: string, durationMs: number | null, widthPx: number | null, heightPx: number | null, available: boolean, };

export type CaptureSummary = { id: CaptureId, kind: CaptureKind, context: ContextRef, branchName: string | null, capturedAt: Timestamp, textExcerpt: string | null, caption: string | null, captionSource: CaptionSource | null, media: MediaSummary | null, };

export type CaptureDetail = { id: CaptureId, kind: CaptureKind, context: ContextRef, branchName: string | null, capturedAt: Timestamp, textExcerpt: string | null, caption: string | null, captionSource: CaptionSource | null, media: MediaSummary | null, textBody: string | null, sourceApp: string | null, sourceWindowTitle: string | null, updatedAt: Timestamp, enrichmentStatus: EnrichmentStatus, };

export type Page<T> = { items: Array<T>, nextCursor: string | null, };

export type SaveTextCaptureInput = { sessionId: CaptureSessionId, textBody: string, };

export type StageClipboardImageInput = { sessionId: CaptureSessionId, };

export type DiscardStagedMediaInput = { sessionId: CaptureSessionId, stagedMediaId: StagedMediaId, };

export type SaveImageCaptureInput = { sessionId: CaptureSessionId, stagedMediaId: StagedMediaId, caption: string | null, };

export type StartAudioRecordingInput = { sessionId: CaptureSessionId, inputDeviceId: string | null, };

export type StopAudioRecordingInput = { sessionId: CaptureSessionId, };

export type SaveAudioCaptureInput = { sessionId: CaptureSessionId, stagedMediaId: StagedMediaId, caption: string | null, };

export type PlayStagedAudioInput = { sessionId: CaptureSessionId, stagedMediaId: StagedMediaId, };

export type StopAudioPlaybackInput = { playbackTargetId: string, };

export type AudioPlaybackResult = { playing: boolean, durationMs: number | null, };
